<?php

use Illuminate\Database\Seeder;

class EmployeetotestTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'53',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
            
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'43',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'32',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
          DB::table('employeetotest')->insert([
            'nee_is_employee'=>'19',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'13',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'5',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'3',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'7',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'12',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'6',
            'nee_by_employee'=>'46',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'5',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'2',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'1',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'52',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'51',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'50',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'49',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'48',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'47',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'6',
            'nee_by_employee'=>'7',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'7',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'8',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'6',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'46',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'2',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'12',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'45',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'44',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'42',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'3',
            'nee_by_employee'=>'5',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'41',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'40',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'39',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'38',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'37',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'36',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'35',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'9',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'12',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'6',
            'nee_by_employee'=>'10',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'34',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'33',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'31',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'30',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'29',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'4',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'10',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'8',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'12',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'6',
            'nee_by_employee'=>'9',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'28',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'27',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'26',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'23',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'24',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'25',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'5',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'9',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'12',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'6',
            'nee_by_employee'=>'8',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'22',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'21',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'20',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'46',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'5',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'7',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'10',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'9',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'8',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'6',
            'nee_by_employee'=>'12',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'59',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'18',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'58',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'57',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'55',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'17',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'16',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'6',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'56',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'54',
            'nee_by_employee'=>'11',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'5',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'7',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'9',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'8',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'12',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'15',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'14',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'16',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'17',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);
         DB::table('employeetotest')->insert([
            'nee_is_employee'=>'18',
            'nee_by_employee'=>'6',
            'nee_id_form'=>'1',
        ]);



    }
}
