<?php

use Illuminate\Database\Seeder;

class NationalityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('nationality')->insert([
            'name'=>'โปรตุเกส', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'ดัตช์', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'เยอรมัน', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'ฝรั่งเศส', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'เดนมาร์ก', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'สวีเดน', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'สวิส', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'อิตาลี', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'นอร์เวย์', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'ออสเตรีย', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'ไอริช', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'ฟินแลนด์', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'เบลเยียม', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'สเปน', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'รัสเซีย', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'โปแลนด์', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'เช็ก', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'ฮังการี', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'กรีก', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'อเมริกัน', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'แคนาดา', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'เม็กซิโก', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'อาร์เจนตินา', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'บราซิล', 
        ]);
        DB::table('nationality')->insert([
        	'name'=>'ชิลี', 
        ]);
        DB::table('nationality')->insert([
            'name'=>'โคลัมเบีย',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ปานามา',
        ]);
        DB::table('nationality')->insert([
            'name'=>'อุรุกวัย',
        ]);
        DB::table('nationality')->insert([
            'name'=>'จีน',
        ]);
        DB::table('nationality')->insert([
            'name'=>'อินเดีย',
        ]);
        DB::table('nationality')->insert([
            'name'=>'เวียดนาม',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ญี่ปุ่น',
        ]);
        DB::table('nationality')->insert([
            'name'=>'พม่า',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ฟิลิปปิน',
        ]);
        DB::table('nationality')->insert([
            'name'=>'มาเลเซีย',
        ]);
        DB::table('nationality')->insert([
            'name'=>'อินโดนีเซีย',
        ]);
        DB::table('nationality')->insert([
            'name'=>'เกาหลีใต้',
        ]);
        DB::table('nationality')->insert([
            'name'=>'สิงคโปร์',
        ]);
        DB::table('nationality')->insert([
            'name'=>'เนปาล',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ลาว',
        ]);
        DB::table('nationality')->insert([
            'name'=>'กัมพูชา',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ศรีลังกา',
        ]);
        DB::table('nationality')->insert([
            'name'=>'แอฟริกาใต้',
        ]);
        DB::table('nationality')->insert([
            'name'=>'สหรัฐอาหรับเอมิเรตส์',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ออสเตรเลีย',
        ]);
        DB::table('nationality')->insert([
            'name'=>'นิวซีแลนด์',
        ]);
        DB::table('nationality')->insert([
            'name'=>'จีน',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ไทย',
        ]);
        DB::table('nationality')->insert([
            'name'=>'เกาหลีเหนือ',
        ]);
        DB::table('nationality')->insert([
            'name'=>'มัลดีฟ',
        ]);
        DB::table('nationality')->insert([
            'name'=>'มองโกเลีย',
        ]);
        DB::table('nationality')->insert([
            'name'=>'โมนาโก',
        ]);
        DB::table('nationality')->insert([
            'name'=>'โดมินิกัน',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ไทยใหญ่',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ไทยลื้อ',
        ]);
        DB::table('nationality')->insert([
            'name'=>'มอญ',
        ]);
        DB::table('nationality')->insert([
            'name'=>'ไม่ระบุ',
        ]);
    }

}
