<?php

use Illuminate\Database\Seeder;

class Ngg_employeeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'แคน',
            'nem_code'=>'91112',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เขม',
            'nem_code'=>'91238',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เอ',
            'nem_code'=>'91111',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'พร',
            'nem_code'=>'61145',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เดีย',
            'nem_code'=>'91077',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เอ๋',
            'nem_code'=>'62052',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เบริด์',
            'nem_code'=>'91086',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ต้อม',
            'nem_code'=>'21003',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'โต้ง',
            'nem_code'=>'61055',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เกียรติ',
            'nem_code'=>'51043',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'หนุ่ย',
            'nem_code'=>'81075',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ใหม่',
            'nem_code'=>'94001',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'กาญจน์',
            'nem_code'=>'91264',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'แพน',
            'nem_code'=>'51171',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ดี',
            'nem_code'=>'51062',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ปู',
            'nem_code'=>'51193',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ตุ๊ก',
            'nem_code'=>'41012',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'หญิง',
            'nem_code'=>'81057',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เอ',
            'nem_code'=>'91066',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ป๊อป',
            'nem_code'=>'94005',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เอ็ม',
            'nem_code'=>'94003',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'อั้ม',
            'nem_code'=>'94002',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ตึ๋ง',
            'nem_code'=>'61007',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ษา',
            'nem_code'=>'61161',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'บี',
            'nem_code'=>'61163',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ต้อง',
            'nem_code'=>'21008',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เนส',
            'nem_code'=>'21007',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'นัท',
            'nem_code'=>'21004',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'อ๋อ',
            'nem_code'=>'61024',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'แอ่ว',
            'nem_code'=>'61003',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ต่อ',
            'nem_code'=>'61197',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'หุ้ง',
            'nem_code'=>'91248',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เสาร์',
            'nem_code'=>'61079',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ดี่',
            'nem_code'=>'61046',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เก๋',
            'nem_code'=>'51067',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'อร',
            'nem_code'=>'51037',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'สันติ',
            'nem_code'=>'51019',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'แอน',
            'nem_code'=>'51009',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ติ๊ก',
            'nem_code'=>'51018',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เบี้ยว',
            'nem_code'=>'51006',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ปุ่น',
            'nem_code'=>'51001',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'โฟกัส',
            'nem_code'=>'91201',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ฮง',
            'nem_code'=>'91258',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'แพร',
            'nem_code'=>'61119',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'บอย',
            'nem_code'=>'91005',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'สมชาติ',
            'nem_code'=>'91006',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เอ๋',
            'nem_code'=>'91265',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ออฟ',
            'nem_code'=>'91221',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'โบ',
            'nem_code'=>'91099',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'เปรม',
            'nem_code'=>'91247',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ตี๋',
            'nem_code'=>'91135',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'แจ๊ค',
            'nem_code'=>'91118',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'หญิง',
            'nem_code'=>'91129',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'หนิง',
            'nem_code'=>'42143',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'หนา',
            'nem_code'=>'41002',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'แพรว',
            'nem_code'=>'21001',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'วิ',
            'nem_code'=>'81071',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ฤทธิ์',
            'nem_code'=>'81067',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'ชีพ',
            'nem_code'=>'81047',
        ]);
        DB::table('ngg_employee')->insert([
            'nem_nickname'=>'',
            'nem_code'=>'',
        ]);
    }
}
